apiVersion: app.k8s.io/v1beta1
kind: Application
metadata:
  annotations:
    apps.open-cluster-management.io/deployables: ''
  name: cheese-quizz-uat
  namespace: cheese-quizz-uat
spec:
  componentKinds:
    - group: apps.open-cluster-management.io
      kind: Subscription
  descriptor: {}
  selector:
    matchExpressions:
      - key: app
        operator: In
        values:
          - cheese-quizz-uat
---
apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  labels:
    app: cheese-quizz-uat
  name: cheese-quizz-placement-uat
  namespace: cheese-quizz-uat
spec:
  clusterSelector:
    matchLabels:
      'local-cluster': 'true'
---
apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  annotations:
    apps.open-cluster-management.io/git-branch: ''
    apps.open-cluster-management.io/git-path: ./overlays/uat
  labels:
    app: cheese-quizz-uat
  name: cheese-quizz-subscription-uat
  namespace: cheese-quizz-uat
spec:
  channel: githubcom-julienbell-cheese-quizz-gitops-ns/githubcom-julienbell-cheese-quizz-gitops
  placement:
    placementRef:
      kind: PlacementRule
      name: cheese-quizz-placement-uat