kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: admin
  namespace: cheese-quizz
subjects:
  - kind: User
    apiGroup: rbac.authorization.k8s.io
    name: John-srv-ops
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: admin